# Generated by Django 3.1.1 on 2021-02-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee_razorpay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('amount', models.CharField(max_length=254)),
                ('payment_id', models.CharField(max_length=14)),
            ],
        ),
    ]
