# Generated by Django 3.1.1 on 2021-02-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee_razorpay',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coffee_razorpay',
            name='razorpay_id',
            field=models.CharField(blank=True, default=True, max_length=100),
        ),
    ]
