# Generated by Django 3.1.1 on 2021-02-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210222_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee_razorpay',
            name='razorpay_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
